apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-6laa
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0074-tenant/tkrw-pr712-0075-0074-app/devfile-sample-6laa@sha256:20b5073e0fd2eef4f9ed6cc1b72ae451a5e030a6785a66dd65507ae88a97ebcf
        name: my-nodejs
        resources: {}
status: {}
